# H2 Database Configuration (Dev Profile)
spring.datasource.url=jdbc:h2:mem:stagedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
logging.level.cm.univ.maroua.enspm.stage=debug

# Graceful shutdown configuration for scheduled tasks
spring.task.execution.shutdown.await-termination=true
spring.task.execution.shutdown.await-termination-period=60s
spring.task.scheduling.shutdown.await-termination=true
spring.task.scheduling.shutdown.await-termination-period=60s

spring.mail.properties.mail.debug=true

# Planification quotidienne à 07h00 (création des messages en attente)
app.notification.cron.planifier=0 0/5 * * * ?
